### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by thomas-frantz** [cooperl22/laravel-ibmi#1]
I've noticed there's a branch for 5, is this working? How might I go about installing this in 5?

I'm having to write some integration with our iSeries into Laravel, so if this can work with Laravel 5 this seems like it would be perfect!

Thanks

Edit: Also I realize this was released/updated 8 days ago, and I appreciate the effort going into it! There seems to be few resources for iSeries and PHP integration out there.

**Comment by cooperl22** [comment]
Hi @Coreinsanity 

Yes it works with Laravel 5.

Just add this to your composer.json file:

``` json
"cooperl/laravel-ibmi": "dev-laravel5"
```

**Comment by bskimball** [comment]
cooperl/laravel-ibmi: dev-laravel5 is not found using composer.

Is there a package for laravel5?

**Comment by cooperl22** [comment]
Hello.

This package works with Laravel 5 since the release 2.0.

Best regards,

Le jeu. 13 août 2015 à 17:53, bskimball notifications@github.com a écrit :

> cooperl/laravel-ibmi: dev-laravel5 is not found using composer.
> 
> Is there a package for laravel5?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cooperl22/laravel-ibmi/issues/1#issuecomment-130735922
> .

## 

_"Ce message et toutes les pièces jointes (ci-après le "message") sont 
établis à l'intention exclusive de ses destinataires et sont confidentiels. 
Si vous recevez ce message par erreur, merci de le détruire et d'en avertir 
immédiatement l’expéditeur. Toute utilisation de ce message non conforme à 
sa destination, toute diffusion ou toute publication, totale ou partielle, 
est interdite, sauf autorisation expresse. L'internet ne permettant pas 
d'assurer l'intégrité de ce message, nous déclinons toute responsabilité au 
titre de ce message, dans l’hypothèse où il aurait été modifié."_
